# Generated by Django 3.2.3 on 2021-06-27 04:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 27, 4, 53, 57, 378742, tzinfo=utc), null=True),
        ),
    ]
